name: portfolio
description: Jens Becker portfolio page, visit jensbecker.dev

publish_to: none

version: 1.0.0+1

environment:
  sdk: ">=2.16.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  font_awesome_flutter: ^10.1.0
  url_launcher: ^6.0.20
  # See https://github.com/material-foundation/google-fonts-flutter/pull/195
  google_fonts:
    git:
      url: https://github.com/material-foundation/google-fonts-flutter
      ref: proposal-awaitFontLoads
  beamer: ^1.4.0+1
  scroll_to_index: ^2.1.1
  firebase_core: ^1.19.2
  cloud_firestore: ^3.1.11
  flutter_hooks: ^0.18.2+1
  flutter_html: ^3.0.0-alpha.2
  flutter_svg: ^1.0.3
  easy_localization: ^3.0.0
  flutter_staggered_grid_view: ^0.6.1
  fleasy: ^0.13.0


flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/images/badges/de/
    - assets/images/badges/en/
    - assets/images/projects/icons/
    - assets/images/projects/mockups/
    - assets/images/tools_icons/
    - assets/translations/
