name: portfolio
description: Jens Becker portfolio page, visit jensbecker.dev

publish_to: none

version: 1.0.0+1

environment:
  sdk: ">=2.15.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  font_awesome_flutter: ^9.2.0
  url_launcher: ^6.0.18
  # See https://github.com/material-foundation/google-fonts-flutter/pull/195
  google_fonts:
    git:
      url: https://github.com/material-foundation/google-fonts-flutter
      ref: proposal-awaitFontLoads
  beamer: ^1.2.0
  scroll_to_index: ^2.1.1
  firebase_core: ^1.12.0
  cloud_firestore: ^3.1.7
  flutter_hooks: ^0.18.2
  flutter_html: ^3.0.0-alpha.2
  flutter_svg: ^1.0.3
  easy_localization: ^3.0.0
  fleasy: ^0.10.0


flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/images/badges/de/
    - assets/images/badges/en/
    - assets/images/projects/icons/
    - assets/images/projects/mockups/
    - assets/images/tools_icons/
    - assets/translations/